"""Assemble S1 Data, the Supporting Information package that accompanies the manuscript.

Copies the inputs, the values behind every figure panel, and the tables and draws the text
cites into S1_Data/, and writes S1_Data/README.md listing what each file is.  The folder is
generated, not kept under version control: run `python scripts/make_s1_data.py` (or `make
s1data`) after `python run_all.py`.
"""
import _path  # noqa: F401
import os, shutil, json
from esbm import ROOT, RESULTS, S1DATA
FIGDATA = os.path.join(ROOT, "figdata")
DATA = os.path.join(ROOT, "data")

ITEMS = [
    ("data/jiangninfa2011_fig2B_digitised.csv", "the twelve digitized points of the first-layer titration (Jiang & Ninfa 2011, Fig 2B)"),
    ("data/published_constants.json", "the published Hill coefficients, half-points, concentrations and affinities used"),
    ("results/revision_numbers.json", "every quantity the text quotes: fit, model comparison, profiles, cascade accounting, perturbation summaries"),
    ("results/counterexamples_parameters.json", "rate constants, totals and 60-digit roots of each multistationary example"),
    ("results/conversion_factor.json", "the conversion between a reported coefficient and the local ladder factor, on three ladder families and the full locus"),
    ("results/nu2_major2.json", "the cascade composite when the downstream ladder is non-binomial"),
    ("results/fit_titration.json", "the model comparison, profile likelihood and residual diagnostics of the titration refit"),
    ("results/verify_symbolic.json", "the computer-algebra checks of the identities"),
    ("results/mono_adversarial.json", "the adversarial search for non-monotone total effector"),
]

def main():
    os.makedirs(S1DATA, exist_ok=True)
    for f in os.listdir(S1DATA):
        if f != "README.md": os.remove(os.path.join(S1DATA, f))
    rows = []
    for rel, what in ITEMS:
        src = os.path.join(ROOT, rel)
        if not os.path.exists(src):
            print("  missing (run run_all.py first):", rel); continue
        dst = os.path.join(S1DATA, os.path.basename(rel)); shutil.copy(src, dst)
        rows.append((os.path.basename(rel), what))
    for f in sorted(os.listdir(FIGDATA)):
        if not f.endswith(".csv"): continue
        shutil.copy(os.path.join(FIGDATA, f), os.path.join(S1DATA, f))
        with open(os.path.join(FIGDATA, f)) as fh: first = fh.readline().strip()
        rows.append((f, first.lstrip("# ")))
    with open(os.path.join(S1DATA, "README.md"), "w") as f:
        f.write("# S1 Data\n\nGenerated by `scripts/make_s1_data.py` from the repository at the commit named in the\n"
                "manuscript's data availability statement. Every file is an output of the code, except the two\n"
                "inputs at the top of the table.\n\n| file | content |\n|---|---|\n")
        for name, what in rows: f.write("| `%s` | %s |\n" % (name, what))
    print("S1 Data: %d files in %s" % (len(rows)+1, os.path.relpath(S1DATA, ROOT)))

if __name__ == "__main__":
    main()
